language: objective-c
os: osx
osx_image: xcode8

env:
  matrix:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - TEST_TYPE=iOS
    - TEST_TYPE=macOS
-before_install:
 - |
    brew install carthage
    carthage update

script:
- |
    if [ "$TEST_TYPE" = iOS ]; then
      set -o pipefail
      xcodebuild clean test -project CacheLeaf.xcodeproj -scheme CacheLeaf -destination "platform=iOS Simulator,name=iPhone 6 Plus" -enableCodeCoverage YES | xcpretty
    elif [ "$TEST_TYPE" = macOS ]; then
      set -o pipefail
      xcodebuild clean test -project CacheLeaf.xcodeproj -scheme CacheLeaf-macOS -sdk macosx -enableCodeCoverage YES | xcpretty
    fi
after_success:
- |
    if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = macOS ] then
      bash <(curl -s https://codecov.io/bash)
    fi
    sleep 10
